name:                typelits-printf
version:             0.1.0.0
github:              "mstksg/typelits-printf"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Type-safe printf from parsing GHC Typelits
category:            Text

description: |
  An extensible and type-safe printf, matching the semantics of 'P.printf'
  from "Text.Printf" in /base/.  The difference is that the variants here will
  always fail to compile if given arguments of the wrong type (or too many or
  too little arguments).  Most of the variants also provide useful type
  feedback, telling you the type of arguments it expects and how many when
  queried with @:t@ or with typed holes.

  See README and documentation of "GHC.TypeLits.Printf" for more information

ghc-options:
- -Wall
- -Wcompat
# - -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
  - GHC.TypeLits.Printf.Internal
  - GHC.TypeLits.Printf.Internal.Parser
  - GHC.TypeLits.Printf.Parse
  dependencies:
  - symbols
  - text
  - vinyl
